---
AllCops:
  SuggestExtensions: false
  NewCops: enable

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
